---
- name: Creates directory
  become: yes
  file:
    path: "/srv/stg"
    state: "directory"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy compressed backend folder
  copy:
    src: "/home/circleci/source/artifact.tar.gz"
    dest: "/srv/stg"

- name: Extract artifact
  unarchive:
    src: "/srv/stg/artifact.tar.gz"
    dest: "/srv/stg"
    remote_src: yes

- name: Start application
  command: |
    cd /srv/stg
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: "/srv/stg"
