- name: "Create server directory"
  file:
    path: "~/server"
    state: "directory"
    mode: 0755

- name: "Compress and copy backend file"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "~/server/artifact-backend.tar.gz"

- name: "Extract backend to folder"
  unarchive:
    remote_src: yes
    src: "~/server/artifact-backend.tar.gz"
    dest: "~/server"

- name: "Start web server"
  shell:
    cmd: |
      cd ~/server
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready
